import React, { useMemo, useState } from 'react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const FEATURES = [
  { id: 'study_hours', label: 'Study hours', unit: 'hours' },
  { id: 'attendance', label: 'Attendance', unit: '%' },
  { id: 'previous_marks', label: 'Previous marks', unit: '%' },
];

export default function LivePredictionCharts({ sensitivity, prediction, selectedModel, inputs }) {
  const [feature, setFeature] = useState('study_hours');
  const modelLabel = selectedModel === 'linear_regression' ? 'Linear Regression' : 'Decision Tree';
  const curve = sensitivity?.curves?.[feature];
  const current = inputs || sensitivity?.baseline_inputs;
  const rows = useMemo(() => (curve?.points || []).map((p) => ({
    ...p,
    probability: +(Number(p.pass_probability || 0) * 100).toFixed(2),
    pointLabel: p.is_current ? 'Your input' : '',
  })), [curve]);
  const activeFeature = FEATURES.find((f) => f.id === feature) || FEATURES[0];

  if (!prediction || !sensitivity) {
    return <section className="rounded-3xl border border-white/10 bg-black/30 p-6">
      <h2 className="text-xl font-bold text-white">Live model response</h2>
      <p className="mt-2 text-sm text-neutral-400">Run a prediction first. This chart will then query the selected model across input ranges while holding the other two values fixed.</p>
    </section>;
  }

  return <section className="space-y-5">
    <div className="rounded-3xl border border-white/10 bg-black/30 p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs uppercase tracking-wider text-yellow-300/70">Live prediction analytics</p>
          <h2 className="mt-1 text-xl font-bold text-white">{modelLabel} response curve</h2>
          <p className="mt-2 max-w-3xl text-sm leading-relaxed text-neutral-400">{sensitivity.note} The curve is generated by the backend model, not a static training-data chart.</p>
        </div>
        <span className="rounded-full border border-yellow-400/30 bg-yellow-400/10 px-3 py-1.5 text-xs font-semibold text-yellow-200">{prediction.predicted_result} · {(Number(prediction.pass_probability || 0) * 100).toFixed(1)}% pass probability</span>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3">
        {FEATURES.map((f) => <button key={f.id} onClick={() => setFeature(f.id)} className={`rounded-xl border px-4 py-3 text-left transition ${feature === f.id ? 'border-yellow-400/50 bg-yellow-400/10 text-yellow-100' : 'border-white/10 bg-white/[0.02] text-neutral-300 hover:bg-white/[0.05]'}`}>
          <span className="block text-xs text-neutral-500">{f.label}</span>
          <span className="mt-1 block font-mono text-lg font-semibold">{Number(current?.[f.id] ?? 0)}{f.id === 'study_hours' ? ' h' : '%'}</span>
        </button>)}
      </div>
      <div className="mt-5 h-[340px]">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={rows} margin={{ top: 16, right: 20, bottom: 14, left: 4 }}>
            <CartesianGrid strokeDasharray="3 5" stroke="#292929" />
            <XAxis type="number" dataKey="value" domain={['dataMin', 'dataMax']} stroke="#777" fontSize={11} label={{ value: activeFeature.label + (activeFeature.unit ? ' (' + activeFeature.unit + ')' : ''), position: 'insideBottom', offset: -8, fill: '#888' }} />
            <YAxis domain={[0, 100]} stroke="#777" fontSize={11} unit="%" label={{ value: 'Pass probability', angle: -90, position: 'insideLeft', fill: '#888' }} />
            <Tooltip contentStyle={{ background: '#111', border: '1px solid rgba(255,255,255,.15)', borderRadius: 12, color: '#eee', fontSize: 12 }} formatter={(v, name) => [Number(v).toFixed(2) + '%', name]} labelFormatter={(v) => activeFeature.label + ': ' + v} />
            <ReferenceLine x={Number(curve?.current_value)} stroke="#e9bd54" strokeDasharray="5 5" label={{ value: 'Your input', fill: '#e9bd54', fontSize: 11, position: 'insideTopRight' }} />
            <Line type="monotone" dataKey="probability" name="Pass probability" stroke="#e9bd54" strokeWidth={3} dot={(props) => props.payload?.is_current ? { ...props, r: 7, fill: '#fff', stroke: '#e9bd54', strokeWidth: 3 } : false} activeDot={{ r: 6, fill: '#fff', stroke: '#e9bd54', strokeWidth: 2 }} />
          </LineChart>
        </ResponsiveContainer>
      </div>
      <div className="mt-4 grid gap-3 sm:grid-cols-3">
        {FEATURES.filter((f) => f.id !== feature).map((f) => <div key={f.id} className="rounded-xl border border-white/5 bg-white/[0.02] p-3">
          <p className="text-xs text-neutral-500">Held fixed · {f.label}</p><p className="mt-1 font-mono text-sm text-neutral-200">{Number(current?.[f.id] ?? 0)}{f.id === 'study_hours' ? ' hours' : '%'}</p>
        </div>)}
      </div>
      <p className="mt-4 text-xs text-neutral-500">Changing the model selector and running Predict refreshes this chart with that model's response. This is model sensitivity, not proof that changing a student's behavior will cause that outcome.</p>
    </div>
  </section>;
}
