import React,{useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {ArrowLeft,RefreshCw,CloudSun,ChartNoAxesCombined,Users,GraduationCap,BrainCircuit,Activity,Database} from "lucide-react";
const API=(import.meta.env.VITE_API_URL||"http://localhost:8000/api/v1").replace(/\/$/,"")+"/intelligence";
const CFG={
weather:{title:"Weather Intelligence",icon:CloudSun,fields:[["day_of_year","Day of year",180,1,366],["humidity","Humidity (%)",55,0,100],["rainfall","Rainfall (mm)",0,0,500],["wind_speed","Wind speed",5,0,250]],path:"/weather/predict",unit:"°C"},
sales:{title:"Sales Intelligence",icon:ChartNoAxesCombined,fields:[["price","Price",30,0,100000],["promotion","Promotion (0/1)",0,0,1],["ad_spend","Advertising spend",100,0,10000000],["season","Seasonality (-1 to 1)",0,-1,1]],path:"/sales/predict",unit:"sales units"},
customers:{title:"Customer Intelligence",icon:Users,fields:[["annual_spend","Annual spend",800,0,100000000],["orders_per_year","Orders per year",12,0,10000],["avg_order_value","Average order value",75,0,1000000],["days_since_last_order","Days since last order",30,0,3650]],path:"/customers/segment",unit:"cluster"}
};
const MODELS=["Linear Regression","Decision Tree","PCA","K-Means"];
export default function IntelligenceServices(){
 const {serviceId="weather"}=useParams();const c=CFG[serviceId]||CFG.weather;const Icon=c.icon;
 const [v,setV]=useState({});const [model,setModel]=useState(serviceId==="customers"?"K-Means":"Linear Regression");const [result,setResult]=useState(null);const [analytics,setAnalytics]=useState(null);const [busy,setBusy]=useState(false);const [training,setTraining]=useState(false);const [err,setErr]=useState("");const [msg,setMsg]=useState("");
 useEffect(()=>{setV(Object.fromEntries(c.fields.map(f=>[f[0],String(f[2])])));setResult(null);setErr("");setMsg("");setModel(serviceId==="customers"?"K-Means":"Linear Regression");loadAnalytics();},[serviceId]);
 async function loadAnalytics(){try{const r=await fetch(API+"/"+serviceId+"/analytics");const d=await r.json();if(r.ok)setAnalytics(d)}catch{}}
 async function train(){setTraining(true);setErr("");setMsg("");try{const r=await fetch(API+"/train/"+serviceId,{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.detail||"Training failed");setAnalytics(d);setMsg("Training completed independently for "+c.title+". The four model artifacts and held-out regression metrics are refreshed.");}catch(e){setErr(e.message+" — check backend URL and server logs.");}finally{setTraining(false)}}
 async function predict(e){e.preventDefault();setBusy(true);setErr("");try{const body=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,Number(x)]));body.model=model;const r=await fetch(API+c.path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||"Inference failed");setResult(d)}catch(e){setErr(e.message+" — check backend URL and server logs.");}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[var(--bg)] px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-7xl">
 <header className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><Link to="/" className="mb-4 inline-flex items-center gap-2 text-sm text-neutral-400 hover:text-yellow-300"><ArrowLeft size={16}/> All services</Link><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-yellow-400/10 text-yellow-300"><Icon size={25}/></div><div><p className="text-xs uppercase tracking-[.2em] text-yellow-400">Dedicated workspace</p><h1 className="text-3xl font-bold">{c.title}</h1></div></div><p className="mt-3 text-neutral-400">Independent dataset, training, model registry, prediction and evaluation.</p></div><Link to="/grade" className="rounded-xl border border-white/15 px-4 py-3 text-sm hover:bg-white/10"><GraduationCap className="mr-2 inline" size={16}/> Grade Intelligence</Link></header>
 <div className="mb-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><Database className="mb-3 text-yellow-300"/><p className="text-sm text-neutral-400">Dataset</p><p className="mt-1 font-semibold">Separate service dataset</p><p className="mt-1 text-xs text-neutral-500">Synthetic demo rows, independently regenerated</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><BrainCircuit className="mb-3 text-yellow-300"/><p className="text-sm text-neutral-400">Model suite</p><p className="mt-1 font-semibold">4 model families</p><p className="mt-1 text-xs text-neutral-500">Linear Regression · Decision Tree · PCA · K-Means</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><Activity className="mb-3 text-yellow-300"/><p className="text-sm text-neutral-400">Training pipeline</p><p className="mt-1 font-semibold">{analytics?"Metrics available":"Training not yet run"}</p><button onClick={train} disabled={training} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-yellow-400 px-3 py-2 text-sm font-semibold text-black disabled:opacity-50"><RefreshCw size={14} className={training?"animate-spin":""}/>{training?"Training…":"Train / retrain this service"}</button></div></div>
 {msg&&<div role="status" className="mb-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-300">{msg}</div>}{err&&<div role="alert" className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{err}</div>}
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/[.035] p-6 sm:p-8"><p className="text-xs uppercase tracking-[.2em] text-yellow-400">Inference</p><h2 className="mt-2 text-2xl font-bold">Configure analysis</h2><form onSubmit={predict} className="mt-6 space-y-4">{c.fields.map(f=><label key={f[0]} className="block text-sm text-neutral-300">{f[1]}<input type="number" required min={f[3]} max={f[4]} step="any" value={v[f[0]]??f[2]} onChange={e=>setV(x=>({...x,[f[0]]:e.target.value}))} className="mt-1 w-full rounded-xl border border-white/10 bg-black/40 px-3 py-3 text-white outline-none focus:border-yellow-400"/></label>)}<label className="block text-sm text-neutral-300">Selected model<select value={model} onChange={e=>setModel(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-neutral-900 px-3 py-3 text-white">{MODELS.map(m=><option key={m}>{m}</option>)}</select></label><p className="text-xs text-neutral-500">PCA returns a two-dimensional projection; K-Means returns a cluster. They are unsupervised analysis models, not target-value predictors.</p><button disabled={busy} className="w-full rounded-xl bg-yellow-400 px-4 py-3.5 font-bold text-black disabled:opacity-50">{busy?"Running…":"Run selected model"}</button></form></section>
 <section className="rounded-3xl border border-white/10 bg-white/[.035] p-6 sm:p-8"><p className="text-xs uppercase tracking-[.2em] text-yellow-400">Dashboard</p><h2 className="mt-2 text-2xl font-bold">Results & evaluation</h2>{result?<div className="mt-6 rounded-2xl border border-emerald-500/25 bg-emerald-500/10 p-5"><p className="text-sm text-emerald-300">Output · {result.model}</p><p className="mt-2 text-3xl font-bold">{result.prediction!==undefined?String(result.prediction)+" "+c.unit:result.cluster!==undefined?"Cluster "+result.cluster+" / "+result.clusters:result.projection?"PCA projection: "+result.projection.join(", "):"Analysis complete"}</p><p className="mt-3 text-sm text-neutral-300">{result.note||"Model response"}</p><pre className="mt-4 max-h-48 overflow-auto rounded-xl bg-black/30 p-3 text-xs text-neutral-400">{JSON.stringify(result,null,2)}</pre></div>:<div className="mt-6 rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-neutral-500">Run an analysis to see model output here.</div>}
 <h3 className="mt-7 font-semibold">Model registry</h3><div className="mt-3 grid grid-cols-2 gap-3">{MODELS.map(m=><button onClick={()=>setModel(m)} key={m} className={"rounded-xl border p-4 text-left "+(model===m?"border-yellow-400/50 bg-yellow-400/10":"border-white/10 bg-black/20")}><p className="text-sm font-semibold">{m}</p><p className="mt-1 text-xs text-neutral-500">{m==="Linear Regression"?"Regression baseline":m==="Decision Tree"?"Interpretable regression tree":m==="PCA"?"2D feature projection":"Four-cluster segmentation"}</p></button>)}</div>
 <h3 className="mt-7 font-semibold">Held-out model metrics</h3>{analytics?<pre className="mt-3 max-h-72 overflow-auto rounded-xl bg-black/30 p-4 text-xs text-neutral-400">{JSON.stringify(analytics,null,2)}</pre>:<p className="mt-2 text-sm text-neutral-500">Train this service to generate its independent metrics report.</p>}</section></div>
 <p className="mt-8 text-xs leading-relaxed text-neutral-500">Caveat: these services currently train on reproducible synthetic demonstration data. Weather output is not a live meteorological forecast, and sales/customer results are not validated business intelligence. Replace demo data and validate before real operational use.</p></div></main>
}
