import React, { useState } from "react";
import { Link } from "react-router-dom";

const API = (import.meta.env.VITE_API_URL || "http://127.0.0.1:8000").replace(/\/$/, "") + "/api/v1/intelligence";

const SERVICES = [
  {id:"weather",title:"Weather Intelligence",desc:"Estimate temperature from seasonal and atmospheric inputs.",fields:[["day_of_year","Day of year",180,1,366],["humidity","Humidity (%)",55,0,100],["rainfall","Rainfall (mm)",0,0,500],["wind_speed","Wind speed",5,0,250]],endpoint:"/weather/predict",button:"Predict temperature"},
  {id:"sales",title:"Sales Intelligence",desc:"Estimate sales units from pricing, promotion, advertising and seasonality.",fields:[["price","Price",30,0,100000],["promotion","Promotion (0 or 1)",0,0,1],["ad_spend","Advertising spend",100,0,10000000],["season","Seasonality (-1 to 1)",0,-1,1]],endpoint:"/sales/predict",button:"Predict sales"},
  {id:"customers",title:"Customer Intelligence",desc:"Assign a customer profile to one of four K-Means segments.",fields:[["annual_spend","Annual spend",800,0,100000000],["orders_per_year","Orders per year",12,0,10000],["avg_order_value","Average order value",75,0,1000000],["days_since_last_order","Days since last order",30,0,3650]],endpoint:"/customers/segment",button:"Segment customer"}
];

export default function IntelligenceServices(){
 const [values,setValues]=useState(Object.fromEntries(SERVICES.map(s=>[s.id,Object.fromEntries(s.fields.map(f=>[f[0],String(f[2])]))])));
 const [results,setResults]=useState({}); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [training,setTraining]=useState(false); const [trainMsg,setTrainMsg]=useState("");
 const change=(id,key,value)=>setValues(v=>({...v,[id]:{...v[id],[key]:value}}));
 async function submit(s){setBusy(s.id);setError("");try{const response=await fetch(API+s.endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(Object.entries(values[s.id]).map(([k,v])=>[k,Number(v)])))});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Request failed");setResults(r=>({...r,[s.id]:data}));}catch(e){setError(e.message+" — confirm the FastAPI backend is running and VITE_API_URL points to it.");}finally{setBusy("");}}
 async function train(){setTraining(true);setError("");setTrainMsg("");try{const r=await fetch(API+"/train",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Training failed");setTrainMsg("Training completed. Weather, sales and customer models are ready.");}catch(e){setError(e.message);}finally{setTraining(false);}}
 return <main className="min-h-screen bg-neutral-950 px-5 py-10 text-white sm:px-10">
  <div className="mx-auto max-w-7xl">
   <div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-amber-400">GradeAI Platform</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Intelligence Services</h1><p className="mt-2 text-neutral-400">Three new CPU-friendly ML services alongside Grade Intelligence.</p></div><div className="flex gap-3"><Link to="/" className="rounded-xl border border-white/15 px-4 py-2 text-sm hover:bg-white/10">← Grade Intelligence</Link><button onClick={train} disabled={training} className="rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-black disabled:opacity-50">{training?"Training…":"Train / refresh models"}</button></div></div>
   {trainMsg&&<div role="status" className="mb-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-300">{trainMsg}</div>}
   {error&&<div role="alert" className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
   <div className="grid gap-5 lg:grid-cols-3">{SERVICES.map(s=><section key={s.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-6 shadow-xl"><div className="mb-4 text-3xl">{s.id==="weather"?"🌦":s.id==="sales"?"📈":"👥"}</div><h2 className="text-xl font-semibold">{s.title}</h2><p className="mb-6 mt-2 min-h-12 text-sm leading-relaxed text-neutral-400">{s.desc}</p><form onSubmit={e=>{e.preventDefault();submit(s)}} className="space-y-4">{s.fields.map(f=><label key={f[0]} className="block text-sm text-neutral-300"><span>{f[1]}</span><input type="number" required min={f[3]} max={f[4]} step="any" value={values[s.id][f[0]]} onChange={e=>change(s.id,f[0],e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2.5 text-white outline-none focus:border-amber-400"/></label>)}<button disabled={busy===s.id} className="w-full rounded-xl bg-amber-400 px-4 py-3 font-semibold text-black disabled:opacity-50">{busy===s.id?"Running…":s.button}</button></form>
   {results[s.id]&&<div aria-live="polite" className="mt-5 rounded-2xl border border-emerald-500/25 bg-emerald-500/10 p-4"><p className="text-xs uppercase tracking-wide text-emerald-300">Result</p>{s.id==="weather"?<p className="mt-1 text-2xl font-bold">{results[s.id].prediction} °C</p>:s.id==="sales"?<p className="mt-1 text-2xl font-bold">{results[s.id].prediction} sales units</p>:<p className="mt-1 text-2xl font-bold">Customer cluster {results[s.id].cluster} / {results[s.id].clusters}</p>}<p className="mt-2 text-xs text-neutral-400">Model: {results[s.id].model}. Demo-data estimate; not a live forecast or business guarantee.</p></div>}</section>)}</div>
   <p className="mt-8 text-xs leading-relaxed text-neutral-500">The additional services train on separate deterministic synthetic datasets. Weather and sales use a chronological holdout for basic error metrics. For real-world forecasting, replace the demo data with geographically and operationally relevant observations and evaluate on future periods.</p>
  </div>
 </main>
}
