import React from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth.jsx";
import { GraduationCap, CloudSun, ChartNoAxesCombined, Users, ArrowUpRight, BrainCircuit, LogOut, Activity } from "lucide-react";
const services=[
 {id:"grade",title:"Grade Intelligence",description:"Student performance predictions, model comparisons, class analytics and explainability.",icon:GraduationCap,route:"/grade",tag:"Education"},
 {id:"weather",title:"Weather Intelligence",description:"Temperature estimation, weather pattern exploration and model evaluation.",icon:CloudSun,route:"/services/weather",tag:"Climate"},
 {id:"sales",title:"Sales Intelligence",description:"Sales estimation, seasonality analysis, business drivers and model evaluation.",icon:ChartNoAxesCombined,route:"/services/sales",tag:"Business"},
 {id:"customers",title:"Customer Intelligence",description:"Customer segmentation, behavioral profiles, cluster exploration and model evaluation.",icon:Users,route:"/services/customers",tag:"Customers"}
];
export default function ServicesHub(){const {user,logout}=useAuth();return <main className="min-h-screen bg-[var(--bg)] px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-yellow-400 text-black"><BrainCircuit/></div><div><p className="text-xs uppercase tracking-[.24em] text-yellow-400">GradeAI Platform</p><h1 className="text-2xl font-bold">Intelligence Services</h1></div></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-sm font-medium">{user?.full_name||user?.email||"Authenticated user"}</p><p className="text-xs capitalize text-neutral-400">{user?.role||"User"} workspace</p></div><button onClick={()=>logout()} className="rounded-xl border border-white/15 p-3 hover:bg-white/10" aria-label="Sign out"><LogOut size={17}/></button></div></header><section className="py-10"><p className="mb-3 flex items-center gap-2 text-sm text-emerald-300"><Activity size={16}/> Platform workspace</p><h2 className="max-w-3xl text-4xl font-bold leading-tight sm:text-5xl">One platform. Four focused intelligence services.</h2><p className="mt-4 max-w-2xl leading-relaxed text-neutral-400">Choose a service to open its dedicated workspace. Each service maintains independent training, model artifacts, evaluations, predictions and analytics.</p></section><section className="grid gap-5 sm:grid-cols-2">{services.map((s,i)=>{const Icon=s.icon;return <Link key={s.id} to={s.route} className="group rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.07] to-white/[.02] p-6 transition hover:-translate-y-1 hover:border-yellow-400/40 hover:bg-white/[.07] sm:p-8"><div className="flex items-start justify-between"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-yellow-400/10 text-yellow-300"><Icon size={26}/></div><ArrowUpRight className="text-neutral-500 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-yellow-300"/></div><p className="mt-7 text-xs uppercase tracking-[.2em] text-yellow-400">{s.tag} · 0{i+1}</p><h3 className="mt-2 text-2xl font-bold">{s.title}</h3><p className="mt-3 min-h-[3.5rem] leading-relaxed text-neutral-400">{s.description}</p><div className="mt-7 flex items-center justify-between border-t border-white/10 pt-4 text-sm"><span className="text-neutral-300">Open workspace</span><span className="text-yellow-300">Explore service →</span></div></Link>})}</section><p className="mt-8 text-xs text-neutral-500">Model outputs are demonstration estimates until validated against appropriate real-world datasets. Each service displays its dataset and evaluation context.</p></div></main>}
